export interface RoadmapTopic {
  id: string;
  title: string;
  duration: string;
  youtubeUrl: string;
  documentUrl: string;
  completed?: boolean;
}

export interface RoadmapCourse {
  title: string;
  description: string;
  level: string;
  totalHours: string;
  topics: RoadmapTopic[];
  playlistUrl?: string;
  notesZipUrl?: string;
}

/** Universal course/roadmap data — same shape for every path */
export const ROADMAP_DATA: Record<string, RoadmapCourse> = {
  frontend: {
    title: 'Frontend Developer Path',
    description: 'HTML, CSS, modern JavaScript, and React — from zero to polished UIs.',
    level: 'Beginner → Advanced',
    totalHours: '~40 hrs',
    playlistUrl: 'https://www.youtube.com/playlist?list=PL4cUxeGkcC9gZD-Tvwfod2gaISzfRiP9d',
    notesZipUrl: 'https://developer.mozilla.org/en-US/docs/Learn/Front-end_web_developer',
    topics: [
      {
        id: 'fe-1',
        title: 'HTML & Semantic Markup',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=UB1O30fR-EE',
        documentUrl: 'https://developer.mozilla.org/en-US/docs/Learn/HTML',
        completed: true,
      },
      {
        id: 'fe-2',
        title: 'CSS Flexbox, Grid & Responsive',
        duration: '~4 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=1Rs2ND1ryYc',
        documentUrl: 'https://developer.mozilla.org/en-US/docs/Learn/CSS',
        completed: true,
      },
      {
        id: 'fe-3',
        title: 'JavaScript Essentials (ES6+)',
        duration: '~6 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=W6NZfCO5SIk',
        documentUrl: 'https://javascript.info/',
      },
      {
        id: 'fe-4',
        title: 'DOM & Browser APIs',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=0ik6X4DJKCc',
        documentUrl: 'https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model',
      },
      {
        id: 'fe-5',
        title: 'React Fundamentals',
        duration: '~8 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=bMknfKXIFA8',
        documentUrl: 'https://react.dev/learn',
      },
      {
        id: 'fe-6',
        title: 'React Hooks & State',
        duration: '~5 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=TNhaISOUy6Q',
        documentUrl: 'https://react.dev/reference/react',
      },
      {
        id: 'fe-7',
        title: 'Routing & Data Fetching',
        duration: '~4 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=Ul3y1LXxzdU',
        documentUrl: 'https://reactrouter.com/en/main',
      },
      {
        id: 'fe-8',
        title: 'Styling Systems (Tailwind)',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=lCxcTsO1lYU',
        documentUrl: 'https://tailwindcss.com/docs',
      },
      {
        id: 'fe-9',
        title: 'Testing Frontend Apps',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=7dTTFW7yACQ',
        documentUrl: 'https://testing-library.com/docs/react-testing-library/intro/',
      },
      {
        id: 'fe-10',
        title: 'Build & Deploy',
        duration: '~2 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=QwQuro7ekvc',
        documentUrl: 'https://vitejs.dev/guide/',
      },
    ],
  },
  backend: {
    title: 'Backend Developer Path',
    description: 'APIs, databases, auth, and production-ready Node services.',
    level: 'Beginner → Advanced',
    totalHours: '~45 hrs',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLillGF-RfqbYRpji8t4sxUkKjf_25ukJT',
    notesZipUrl: 'https://nodejs.org/en/docs',
    topics: [
      {
        id: 'be-1',
        title: 'Programming & HTTP Basics',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=iYM2zFP3Zn0',
        documentUrl: 'https://developer.mozilla.org/en-US/docs/Web/HTTP',
        completed: true,
      },
      {
        id: 'be-2',
        title: 'Node.js Fundamentals',
        duration: '~5 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=Oe421EPjeBE',
        documentUrl: 'https://nodejs.org/en/learn',
        completed: true,
      },
      {
        id: 'be-3',
        title: 'Express & REST APIs',
        duration: '~6 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=L72fhGm1tfE',
        documentUrl: 'https://expressjs.com/en/starter/installing.html',
      },
      {
        id: 'be-4',
        title: 'SQL Databases',
        duration: '~5 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=HXV3zeQKqGY',
        documentUrl: 'https://www.postgresql.org/docs/',
      },
      {
        id: 'be-5',
        title: 'MongoDB & NoSQL',
        duration: '~4 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=-56x56UppqQ',
        documentUrl: 'https://www.mongodb.com/docs/manual/',
      },
      {
        id: 'be-6',
        title: 'Authentication & JWT',
        duration: '~4 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=mbsmsi7l3r4',
        documentUrl: 'https://jwt.io/introduction',
      },
      {
        id: 'be-7',
        title: 'Validation & Error Handling',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=DX7t9xq9vYI',
        documentUrl: 'https://expressjs.com/en/guide/error-handling.html',
      },
      {
        id: 'be-8',
        title: 'Caching & Performance',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=6FJ-VvTgYz4',
        documentUrl: 'https://redis.io/docs/',
      },
      {
        id: 'be-9',
        title: 'Docker & Deployment',
        duration: '~4 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=3c-iBn73dDE',
        documentUrl: 'https://docs.docker.com/get-started/',
      },
      {
        id: 'be-10',
        title: 'System Design Basics',
        duration: '~5 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=xpDnVSmNFX0',
        documentUrl: 'https://github.com/donnemartin/system-design-primer',
      },
    ],
  },
  'data-analyst': {
    title: 'Data Analyst Path',
    description: 'Python, SQL, cleaning, visualization, and insight storytelling.',
    level: 'Beginner → Pro',
    totalHours: '~35 hrs',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLWKjhJtqVAblvI1i46ScbKV2jHfdhkIja',
    notesZipUrl: 'https://pandas.pydata.org/docs/',
    topics: [
      {
        id: 'da-1',
        title: 'Python Fundamentals',
        duration: '~4 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=_uQrJ0TkZlc',
        documentUrl: 'https://docs.python.org/3/tutorial/',
        completed: true,
      },
      {
        id: 'da-2',
        title: 'Spreadsheets & Data Basics',
        duration: '~2 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=rwbho0CgEAE',
        documentUrl: 'https://support.google.com/docs/answer/6000292',
        completed: true,
      },
      {
        id: 'da-3',
        title: 'SQL Fundamentals',
        duration: '~5 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=HXV3zeQKqGY',
        documentUrl: 'https://www.w3schools.com/sql/',
      },
      {
        id: 'da-4',
        title: 'Pandas & Data Wrangling',
        duration: '~5 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=vmEHCJoftr-k',
        documentUrl: 'https://pandas.pydata.org/docs/user_guide/index.html',
      },
      {
        id: 'da-5',
        title: 'Data Cleaning',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=bDhvCp3AKQY',
        documentUrl: 'https://pandas.pydata.org/docs/user_guide/missing_data.html',
      },
      {
        id: 'da-6',
        title: 'Visualization (Matplotlib / Seaborn)',
        duration: '~4 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=UO98lJQ3QGI',
        documentUrl: 'https://matplotlib.org/stable/tutorials/index.html',
      },
      {
        id: 'da-7',
        title: 'Statistics for Analysts',
        duration: '~4 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=xxpc-HPfVNY',
        documentUrl: 'https://www.khanacademy.org/math/statistics-probability',
      },
      {
        id: 'da-8',
        title: 'Dashboards & Storytelling',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=A2LbB1m1YHk',
        documentUrl: 'https://www.tableau.com/learn/training',
      },
    ],
  },
  cybersecurity: {
    title: 'Cybersecurity Path',
    description: 'Networks, Linux, threats, web security, and defensive ops.',
    level: 'Beginner → Advanced',
    totalHours: '~40 hrs',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLBfTycyssbfQ_ZRu9QD2_9zAd5d6K8v3b',
    notesZipUrl: 'https://owasp.org/www-project-top-ten/',
    topics: [
      {
        id: 'cy-1',
        title: 'Networking Basics',
        duration: '~4 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=qiQR5rTSshw',
        documentUrl: 'https://www.cloudflare.com/learning/network-layer/what-is-a-computer-network/',
        completed: true,
      },
      {
        id: 'cy-2',
        title: 'Linux Essentials',
        duration: '~4 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=ROjZy1WbCIA',
        documentUrl: 'https://ubuntu.com/tutorials/command-line-for-beginners',
        completed: true,
      },
      {
        id: 'cy-3',
        title: 'Threat Fundamentals',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=inWWhr5tnEA',
        documentUrl: 'https://www.cisa.gov/topics/cyber-threats-and-advisories',
      },
      {
        id: 'cy-4',
        title: 'Web Security (OWASP)',
        duration: '~5 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=2_lswM1S264',
        documentUrl: 'https://owasp.org/www-project-top-ten/',
      },
      {
        id: 'cy-5',
        title: 'Cryptography Basics',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=jhXCYgTReLc',
        documentUrl: 'https://www.cloudflare.com/learning/ssl/what-is-encryption/',
      },
      {
        id: 'cy-6',
        title: 'Offensive Security Intro',
        duration: '~5 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=3Kq1MIfTWCE',
        documentUrl: 'https://tryhackme.com/path/outline/jrpenetrationtester',
      },
      {
        id: 'cy-7',
        title: 'Defensive Security & SIEM',
        duration: '~4 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=QQ45xqG3W3E',
        documentUrl: 'https://www.cisa.gov/topics/cybersecurity-best-practices',
      },
      {
        id: 'cy-8',
        title: 'Incident Response',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=GZjl8kP5m4s',
        documentUrl: 'https://www.nist.gov/cyberframework',
      },
    ],
  },
  'ui-ux': {
    title: 'UI/UX Designer Path',
    description: 'Research, wireframes, Figma, systems, and portfolio case studies.',
    level: 'Creative focused',
    totalHours: '~30 hrs',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLW-zSkCnZ-gD8iNi3kL0Tqw1bOZ7h0f5V',
    notesZipUrl: 'https://www.nngroup.com/articles/',
    topics: [
      {
        id: 'ux-1',
        title: 'Design Fundamentals',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=YqQx75OPRa0',
        documentUrl: 'https://www.interaction-design.org/literature/topics/visual-design',
        completed: true,
      },
      {
        id: 'ux-2',
        title: 'UX Research Methods',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=6M5xMdsg-A4',
        documentUrl: 'https://www.nngroup.com/articles/which-ux-research-methods/',
        completed: true,
      },
      {
        id: 'ux-3',
        title: 'Wireframing & Flows',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=qpH7-KFWPt4',
        documentUrl: 'https://www.nngroup.com/articles/wireframing-101/',
      },
      {
        id: 'ux-4',
        title: 'Figma Essentials',
        duration: '~5 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=FTFaQWZBqQ8',
        documentUrl: 'https://help.figma.com/hc/en-us',
      },
      {
        id: 'ux-5',
        title: 'Prototyping & Interactions',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=Cx2dgIBqO6Y',
        documentUrl: 'https://help.figma.com/hc/en-us/articles/360040328114',
      },
      {
        id: 'ux-6',
        title: 'Design Systems',
        duration: '~4 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=wc5krC28ynQ',
        documentUrl: 'https://www.designsystems.com/',
      },
      {
        id: 'ux-7',
        title: 'Accessibility (a11y)',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=zT62eVxShsY',
        documentUrl: 'https://www.w3.org/WAI/fundamentals/',
      },
      {
        id: 'ux-8',
        title: 'Portfolio & Case Studies',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=OWZ9Y9b0v0k',
        documentUrl: 'https://www.nngroup.com/articles/ux-portfolios/',
      },
    ],
  },
  fullstack: {
    title: 'Full Stack Web Development',
    description: 'End-to-end apps: frontend, APIs, databases, deploy, and portfolio.',
    level: 'Beginner → Intermediate',
    totalHours: '~48 hrs',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLillGF-RfqbbnEGy3ROiLWk7JMCuSyQtX',
    notesZipUrl: 'https://developer.mozilla.org/en-US/docs/Learn',
    topics: [
      {
        id: 'fs-1',
        title: 'HTML & CSS Fundamentals',
        duration: '45 min',
        youtubeUrl: 'https://www.youtube.com/watch?v=mU6anWqZJcc',
        documentUrl: 'https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web',
        completed: true,
      },
      {
        id: 'fs-2',
        title: 'JavaScript Essentials',
        duration: '1 hr 15 min',
        youtubeUrl: 'https://www.youtube.com/watch?v=PkZNo7MFNFg',
        documentUrl: 'https://javascript.info/',
        completed: true,
      },
      {
        id: 'fs-3',
        title: 'React Basics',
        duration: '1 hr 30 min',
        youtubeUrl: 'https://www.youtube.com/watch?v=bMknfKXIFA8',
        documentUrl: 'https://react.dev/learn',
      },
      {
        id: 'fs-4',
        title: 'Node.js & Express',
        duration: '1 hr 45 min',
        youtubeUrl: 'https://www.youtube.com/watch?v=Oe421EPjeBE',
        documentUrl: 'https://expressjs.com/',
      },
      {
        id: 'fs-5',
        title: 'Databases (MongoDB)',
        duration: '1 hr 30 min',
        youtubeUrl: 'https://www.youtube.com/watch?v=-56x56UppqQ',
        documentUrl: 'https://www.mongodb.com/docs/manual/',
      },
      {
        id: 'fs-6',
        title: 'Auth & Full CRUD Apps',
        duration: '2 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=KYvWx0rYXwA',
        documentUrl: 'https://www.passportjs.org/docs/',
      },
      {
        id: 'fs-7',
        title: 'Deploy & Portfolio',
        duration: '1 hr',
        youtubeUrl: 'https://www.youtube.com/watch?v=QwQuro7ekvc',
        documentUrl: 'https://docs.netlify.com/',
      },
    ],
  },
  dsa: {
    title: 'DSA Complete Path',
    description: 'Arrays to DP — structured problem-solving for interviews.',
    level: 'Intermediate',
    totalHours: '~60 hrs',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLgUwDviBIf0oF6VWu-S5hG5mYq8oYh8Qq',
    notesZipUrl: 'https://github.com/TheAlgorithms/Python',
    topics: [
      {
        id: 'dsa-1',
        title: 'Arrays & Strings',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=8hly31xKli0',
        documentUrl: 'https://www.geeksforgeeks.org/array-data-structure/',
      },
      {
        id: 'dsa-2',
        title: 'Linked Lists',
        duration: '~4 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=Hj_r2K8Y_8w',
        documentUrl: 'https://www.geeksforgeeks.org/data-structures/linked-list/',
      },
      {
        id: 'dsa-3',
        title: 'Stacks & Queues',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=wjI1WNcIntg',
        documentUrl: 'https://www.geeksforgeeks.org/stack-data-structure/',
      },
      {
        id: 'dsa-4',
        title: 'Trees & Graphs',
        duration: '~6 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=oSWTXtMglKE',
        documentUrl: 'https://www.geeksforgeeks.org/binary-tree-data-structure/',
      },
      {
        id: 'dsa-5',
        title: 'Hashing',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=shs0KM3wE1U',
        documentUrl: 'https://www.geeksforgeeks.org/hashing-data-structure/',
      },
      {
        id: 'dsa-6',
        title: 'Heaps & Priority Queues',
        duration: '~3 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=t0Cq6tVNRBA',
        documentUrl: 'https://www.geeksforgeeks.org/heap-data-structure/',
      },
      {
        id: 'dsa-7',
        title: 'Sorting Algorithms',
        duration: '~4 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=kPRA0W1kECg',
        documentUrl: 'https://www.geeksforgeeks.org/sorting-algorithms/',
      },
      {
        id: 'dsa-8',
        title: 'Searching Algorithms',
        duration: '~2 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=P3YID7liBug',
        documentUrl: 'https://www.geeksforgeeks.org/searching-algorithms/',
      },
      {
        id: 'dsa-9',
        title: 'Greedy Algorithms',
        duration: '~4 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=ARvQQyOZ6Ev',
        documentUrl: 'https://www.geeksforgeeks.org/greedy-algorithms/',
      },
      {
        id: 'dsa-10',
        title: 'Dynamic Programming',
        duration: '~8 hrs',
        youtubeUrl: 'https://www.youtube.com/watch?v=oBt53YbR9Kk',
        documentUrl: 'https://www.geeksforgeeks.org/dynamic-programming/',
      },
    ],
  },
};

/** Backward-compatible aliases used by older links */
export const ROADMAP_ALIASES: Record<string, string> = {
  'data-analyst': 'data-analyst',
  cybersecurity: 'cybersecurity',
  'ui-ux': 'ui-ux',
};
