import { motion } from 'framer-motion';
import {
  MapPin,
  Search,
  Filter,
  Clock,
  Building2,
  IndianRupee,
  ArrowUpRight,
  ShieldCheck,
  Zap,
  Sparkles,
  Target,
  Check,
} from 'lucide-react';
import { Link } from 'react-router-dom';
import { useEffect, useMemo, useState } from 'react';
import { readOnboarding, type InterestTrack } from '../../utils/onboardingStore';
import {
  applyToInternship,
  getApplication,
  hasApplied,
  readApplications,
  statusBadgeClass,
  type InternshipApplication,
} from '../../utils/internshipApplications';
import { industryPostingsAsInternships } from '../../utils/industryStore';

export const INTERNSHIPS = [
  {
    id: '1',
    role: 'Frontend Developer Intern',
    company: 'TechFlow Systems',
    location: 'Bangalore, India (Remote)',
    stipend: '₹25,000 / mo',
    type: 'Full-time',
    duration: '6 Months',
    posted: '2 days ago',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=TF',
    tags: ['React', 'TypeScript', 'Tailwind'],
    sector: 'software',
    verified: true,
    fastTrack: true,
    employeeCount: '500-1000 Employees',
    companylink: 'https://techflow.ai',
  },
  {
    id: '2',
    role: 'Backend Engineering Intern',
    company: 'DataScale AI',
    location: 'Pune, India',
    stipend: '₹30,000 / mo',
    type: 'Full-time',
    duration: '3 Months',
    posted: '5 hours ago',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=DS',
    tags: ['Node.js', 'PostgreSQL', 'Docker'],
    sector: 'software',
    verified: true,
    fastTrack: false,
    employeeCount: '200-500 Employees',
    companylink: 'https://datascale.ai',
  },
  {
    id: '3',
    role: 'UI/UX Design Intern',
    company: 'CreativePulse',
    location: 'Mumbai, India',
    stipend: '₹15,000 / mo',
    type: 'Part-time',
    duration: '4 Months',
    posted: '1 week ago',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=CP',
    tags: ['Figma', 'Prototyping', 'User Research'],
    sector: 'design',
    verified: false,
    fastTrack: false,
    employeeCount: '50-200 Employees',
    companylink: 'https://creativepulse.com',
  },
  {
    id: '4',
    role: 'Fullstack Developer Intern',
    company: 'Nimbus Labs',
    location: 'Hyderabad, India (Remote)',
    stipend: '₹28,000 / mo',
    type: 'Full-time',
    duration: '6 Months',
    posted: '1 day ago',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=NL',
    tags: ['React', 'Node.js', 'MongoDB', 'APIs'],
    sector: 'software',
    verified: true,
    fastTrack: true,
    employeeCount: '100-500 Employees',
    companylink: 'https://nimbuslabs.dev',
  },
  {
    id: '5',
    role: 'Mobile App Intern (React Native)',
    company: 'AppNest',
    location: 'Chennai, India',
    stipend: '₹22,000 / mo',
    type: 'Full-time',
    duration: '4 Months',
    posted: '3 days ago',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=AN',
    tags: ['React Native', 'TypeScript', 'Mobile'],
    sector: 'software',
    verified: true,
    fastTrack: false,
    employeeCount: '50-200 Employees',
    companylink: 'https://appnest.io',
  },
  {
    id: '6',
    role: 'Cybersecurity Analyst Intern',
    company: 'ShieldOps',
    location: 'Delhi NCR, India',
    stipend: '₹27,000 / mo',
    type: 'Full-time',
    duration: '6 Months',
    posted: '4 hours ago',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=SO',
    tags: ['Linux', 'Networking', 'SIEM', 'Security'],
    sector: 'cybersecurity',
    verified: true,
    fastTrack: true,
    employeeCount: '200-500 Employees',
    companylink: 'https://shieldops.sec',
  },
  {
    id: '7',
    role: 'SOC / Threat Detection Intern',
    company: 'BlueTeam Grid',
    location: 'Bangalore, India (Remote)',
    stipend: '₹24,000 / mo',
    type: 'Full-time',
    duration: '3 Months',
    posted: '2 days ago',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=BG',
    tags: ['Linux', 'Networking', 'Web Vulnerabilities', 'Incident Response'],
    sector: 'cybersecurity',
    verified: true,
    fastTrack: false,
    employeeCount: '100-300 Employees',
    companylink: 'https://blueteamgrid.com',
  },
  {
    id: '8',
    role: 'Data Analyst Intern',
    company: 'InsightHive',
    location: 'Gurgaon, India',
    stipend: '₹26,000 / mo',
    type: 'Full-time',
    duration: '5 Months',
    posted: '6 hours ago',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=IH',
    tags: ['SQL', 'Python', 'Visualization', 'Excel'],
    sector: 'data',
    verified: true,
    fastTrack: true,
    employeeCount: '500-1000 Employees',
    companylink: 'https://insighthive.ai',
  },
  {
    id: '9',
    role: 'Business Intelligence Intern',
    company: 'Metricly',
    location: 'Pune, India (Remote)',
    stipend: '₹20,000 / mo',
    type: 'Part-time',
    duration: '4 Months',
    posted: '5 days ago',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=MT',
    tags: ['SQL', 'Power BI', 'Statistics', 'Data Cleaning'],
    sector: 'data',
    verified: false,
    fastTrack: false,
    employeeCount: '50-150 Employees',
    companylink: 'https://metricly.co',
  },
  {
    id: '10',
    role: 'Machine Learning Intern',
    company: 'Vector Labs',
    location: 'Bangalore, India',
    stipend: '₹35,000 / mo',
    type: 'Full-time',
    duration: '6 Months',
    posted: '1 day ago',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=VL',
    tags: ['Python', 'Machine Learning', 'Statistics', 'SQL'],
    sector: 'data',
    verified: true,
    fastTrack: true,
    employeeCount: '200-500 Employees',
    companylink: 'https://vectorlabs.ai',
  },
  {
    id: '11',
    role: 'Cloud / DevOps Intern',
    company: 'CloudTrail India',
    location: 'Hyderabad, India (Remote)',
    stipend: '₹29,000 / mo',
    type: 'Full-time',
    duration: '6 Months',
    posted: '3 days ago',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=CT',
    tags: ['Docker', 'Linux', 'AWS', 'CI/CD'],
    sector: 'software',
    verified: true,
    fastTrack: false,
    employeeCount: '300-800 Employees',
    companylink: 'https://cloudtrail.in',
  },
  {
    id: '12',
    role: 'Product / Growth Intern',
    company: 'Launchpad Co',
    location: 'Mumbai, India (Remote)',
    stipend: '₹18,000 / mo',
    type: 'Part-time',
    duration: '3 Months',
    posted: '1 week ago',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=LC',
    tags: ['Analytics', 'User Research', 'Spreadsheets', 'Presentation'],
    sector: 'product',
    verified: false,
    fastTrack: false,
    employeeCount: '20-100 Employees',
    companylink: 'https://launchpad.co',
  },
];
